### ISSUE TITLE
Sortable pins coordinate fields cannot be manually edited

### ISSUE THREAD

**Issue by marsouin** [erikyo/vsge-mapbox-block#22]
Hi, thanks for this cool plugin! 

I have noticed that setting the coordinates manually in the sortable pins section updates the wrong field, the `setItemData` call is inverted. 

Happy to open a PR if you'd like :)

**Comment by erikyo** [comment]
Hi @marsouin! 

Thanks for bringing this to our attention! We appreciate your feedback.

We absolutely welcome pull requests, and we'd be grateful if you could submit one to address this issue. If you need any assistance or further details to help you with the PR, please don't hesitate to ask. 

Looking forward to your potential contribution, and thank you again for your support.
